---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    kubeless: kafka
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /var/nfs/kubelesspv
    server: 10.0.2.11
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  labels:
    kubeless: zookeeper
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /var/nfs/kubelesspv
    server: 10.0.2.11
